name: Deploy to Github Release
on:
    push:
        branches:
            - main

jobs:
    bundle:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Install Deps and build
              run: |
                  npm ci
                  npm run build

            - name: Upload Assets
              uses: actions/upload-artifact@v4
              with:
                  name: bundle
                  path: './build'

    deploy:
        needs: bundle
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            deployments: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download Plugin
              uses: actions/download-artifact@v4
              with:
                  name: bundle
                  path: './build'

            - name: Get version
              id: version
              run: |
                  echo "VERSION=$(grep -Po 'Version: \K.*' style.css)" >> "$GITHUB_ENV"
              shell: bash

            - name: Zip theme directory
              run: zip -r phf-pro-child-theme.zip . -x '*.git*' -x '.github/**' -x 'composer.json' -x 'composer.lock' -x 'package.json' -x 'package-lock.json' -x 'webpack.config.js' -x 'README.md' -x 'phpcs.xml.dist' -x 'src/*'

            - name: Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  name: Release ${{env.VERSION}}
                  tag_name: ${{env.VERSION}}
                  files: ./phf-pro-child-theme.zip
